<a href="https://colab.research.google.com/github/unitinguncle/Machine-Learning/blob/main/Machine%20Learning%20Numpy%20Basic%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Exercises**

#### Exercise 1: Import the numpy package under the name np

In [ ]:
# Your Code Here
import numpy as np

#### Exercise 2: Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [ ]:
# Your Code Here
X = np.array([1,45,60,90])
print("Sin value = ",np.sin(X))
print("Cos value = ",np.cos(X))
print("Tan value = ",np.tan(X))

Sin value =  [ 0.84147098  0.85090352 -0.30481062  0.89399666]
Cos value =  [ 0.54030231  0.52532199 -0.95241298 -0.44807362]
Tan value =  [ 1.55740772  1.61977519  0.32004039 -1.99520041]


#### Exercise 3: Given an array *X*. Convert angles from radians to degrees.

X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

In [ ]:
# Your Code Here
X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.rad2deg(X)

array([-180.,  -90.,   90.,  180.])

#### Exercise 4: Given an arrya *X*. Convert angles from degrees to radians.

X = np.array([-180.,  -90.,   90.,  180.])

In [ ]:
# Your Code Here
X = np.array([-180., -90., 90., 180.])
np.deg2rad(X)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

#### Exercise 5: Given an array *X*. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of *X*, element-wise. 

X = np.array([-1., 0, 1.])

In [ ]:
# Your Code Here
X = np.array([-1., 0, 1.])
np.sinh(X)
np.cosh(X)
np.tanh(X)

array([-0.76159416,  0.        ,  0.76159416])

#### Exercise 6: Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [ ]:
# Your Code Here
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])
print("Round form - ",np.round(X,1))
print("Ceil form - ",np.ceil(X))
print("Floor form - ",np.floor(X))

Round form -  [ 4.1  2.5 44.5 25.9 -1.1 -9.5 -6.9]
Ceil form -  [ 5.  3. 45. 26. -1. -9. -6.]
Floor form -  [  4.   2.  44.  25.  -2. -10.  -7.]


#### Exercise 7: Given an array *X*. Calculate the difference between neighboring elements, element-wise.

X = np.array([11, 13, 23, 45, 77])

In [ ]:
# Your Code Here
X = np.array([11, 13, 23, 45, 77])
np.diff(X)

array([ 2, 10, 22, 32])

#### Exercise 8: Given two arrays *X* and *Y*. Find the cross product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
np.cross(X,Y)

array([-3,  6, -3])

#### Exercise 9: Given two arrays *X* and *Y*. Find the dot product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
np.dot(X,Y)

32

#### Exercise 10: Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
print(np.divide(X,Y))
print(np.true_divide(X,Y))
print(np.floor_divide(X,Y))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[0 0 0]


#### Exercise 11: Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
np.power(X,Y)

array([  1,  32, 729])

#### Exercise 12: Given one array *X* and Y = 3. Compute the remainder of X / Y element-wise using remainder and fmod functions.


X = np.array([1, 2, 3])

In [ ]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
print(np.mod(X,Y))
print(np.remainder(X,Y))
print(np.fmod(X,Y))

[1 2 3]
[1 2 3]
[1 2 3]


#### Exercise 13:  Given an array *X*. If an element of *X* is smaller than 5, replace it with 4. And if an element of *X* is bigger than 9, replace it with 8.

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [ ]:
# Your Code Here
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
X[X < 5] = 4
X[X > 9] = 8
X

array([8, 4, 8, 4, 8, 8, 4, 5])

#### Exercise 14: Given an array *X*. Compute the square of *X*, element-wise.

X = np.array([2, 3, 4, 5, 6])

In [ ]:
# Your Code Here
X = np.array([2, 3, 4, 5, 6])
np.square(X)

array([ 4,  9, 16, 25, 36])

#### Exercise 15: Given an array *X*. Compute the absolute value of *X*.

X = np.array([[-44, 3], [4, -3]])

In [ ]:
X = np.array([[-44, 3], [4, -3]])
np.abs(X)

array([[44,  3],
       [ 4,  3]])

#### Exercise 16: Given an array *X*. Compute an element-wise indication of the sign of *X*, element-wise.

X = np.array([1, 3, 0, -1, -3])

In [ ]:
# Your Code Here
X = np.array([1, 3, 0, -1, -3])
np.sign(X)

array([ 1,  1,  0, -1, -1])

#### Exercise 17: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
# Your Code Here
X = np.random.uniform(size=(3,3),low=0,high=1)
X

array([[0.94529161, 0.6421294 , 0.22547341],
       [0.22984558, 0.600618  , 0.23786429],
       [0.777127  , 0.32122308, 0.63535071]])

#### Exercise 18: Given an array *gaussian*. How do you get the number of dimensions of the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.ndim

3

#### Exercise 19: Given an array *gaussian*. How do you get the shape of an array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.shape

(2, 3, 4)

#### Exercise 20: Given an array *gaussian*. How do you get the total number of elements in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.size

24

#### Exercise 21: Given an array *gaussian*. How do you get memory consumed by each item in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [ ]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.itemsize

8

#### Exercise 22: Given an array *twenty*. How do you access first two rows and three columns

twenty = (np.arange(4 * 5)).reshape(4, 5)

In [ ]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty[[0,1],:][:,[0,1,2]]

array([[0, 1, 2],
       [5, 6, 7]])

#### Exercise 23: Given an array *twenty*. How do you reverse the order of elements along columns?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
np.fliplr(twenty)

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

#### Exercise 24: Given an array *twenty*. How do you reverse the order of elements along rows?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
np.flip(twenty)

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

#### Exercise 25: Given an array *twenty*. How do you shuffle the array along axis - 0


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [ ]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
np.random.rand(*twenty.shape).argsort(axis=0)

array([[3, 3, 3, 0, 2],
       [1, 2, 2, 2, 0],
       [0, 1, 0, 3, 3],
       [2, 0, 1, 1, 1]])